baseURL = "https://blog.jarinosuke.com/"
languageCode = "ja-jp"
title = "jarinosuke blog"
theme = "hugo-paper"
#enableInlineShortcodes: true

# 投稿のURL構造
[permalinks]
  posts = "/posts/:filename/"

# タクソノミー（タグとカテゴリ）
[taxonomies]
  tag = "tags"
  category = "categories"

# メニュー（任意で追加）
[menu]

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 2


# 各種パラメータ
[params]
  mainSections = ["posts"]
  author = "jarinosuke"
  description = "jarinosuke blog"
  keywords = ["blog", "ios"]
  DateFormat = "2006-01-02"
  
  # Hugo Paper theme specific settings
  color = "linen"  # linen, wheat, gray, light
  avatar = "naokiishikawa0808@gmail.com"
  name = "jarinosuke"
  bio = "iOS Engineer, Tech Enthusiast"
  twitter = "jarinosuke"
  github = "jarinosuke"
  linkedin = "jarinosuke"
  bluesky = "jarinosuke.bsky.social"
  rss = true
  
  # Custom favicon
  favicon = "favicon.ico"
  appleTouchIcon = "apple-touch-icon.png"
  
  # 投稿リストの表示数
  paginate = 10

# Suppress HTML warnings  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true